name: Import User Repository

on:
  workflow_dispatch:
    inputs:
      user_repo_url:
        description: 'User GitHub Repo URL'
        required: true
        type: string
permissions:
  contents: write  # Give write access to repo contents
  issues: write    # Give write access to issues (optional)
  pull-requests: write  # Give write access to pull requests (optional)

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone user repo
        run: |
          git clone ${{ github.event.inputs.user_repo_url }} user-repo
          cp -r user-repo/* .
          cp -r user-repo/.* . || true  # Copy dotfiles (e.g. .gitignore), ignore errors
          rm -rf user-repo

      - name: Push to this repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin
          git clean -fd                   
          git pull --rebase origin main 
          git add .
          git commit -m "Import user repo" || echo "Nothing to commit"
          git push origin HEAD:main

